Fix postal code format
OpenSourcePolitics/decidim-aws pull request #50
Opened 2021-02-18 15:17 UTC by Quentinchampenois

#### What ? Why ? 

Postal code were saved as Integer in `address` field. 

#### Tasks 
- [x] Update postal code field from `Integer` to `String`
- [x] Add migration for updating current postal codes

2021-02-18 19:46 UTC, armandfardeau requested changes
Sorry @Quentinchampenois but I have an error when executing the migration.
Could you check, please?

<img width="801" alt="Capture d’écran 2021-02-18 à 20 45 12" src="https://user-images.githubusercontent.com/20232956/108412701-64301e00-722a-11eb-902b-afe7d63f552c.png">

2021-02-19 11:17 UTC, Quentinchampenois commented
Thanks for the review @armandfardeau, I could not reproduce your error. However, I tried to reduce the chances that it happens again.

I tried to reproduce with existing postal codes, and with a new database too.

2021-02-19 16:56 UTC, paulinebessoles approved these changes
Tested and approved by product! 
With @Quentinchampenois we were wondering if the migration is needed, as it was not requested by the client and may cause some issues.

2021-02-22 17:08 UTC, armandfardeau requested changes

2021-02-22 17:08 UTC, armandfardeau commented on db/migrate/20210218135141_update_postal_code_registration.rb
>      affected_users = users_with_postal_code
why assign value to another var? Use a memoized method or method directly.

2021-02-22 17:08 UTC, armandfardeau commented on db/migrate/20210218135141_update_postal_code_registration.rb
> +    end
```suggestion
      return if affected_users.empty
```
No need to puts empty values. Empty is sufficient.

2021-02-22 17:08 UTC, armandfardeau commented on db/migrate/20210218135141_update_postal_code_registration.rb
> +      next unless user[:address]['postal_code'].present?
```suggestion
      next unless user.dig(:address, :postal_code).present?
```

2021-02-22 17:08 UTC, armandfardeau commented on db/migrate/20210218135141_update_postal_code_registration.rb
> +    end
There is no need to overcheck for type, either postal code is an integer, then you can cast it to a string, or it's an integer, and you may cast it to a string.

Rails will run this migration into a transaction, if this fails we may fix it properly.

2021-03-08 10:21 UTC, Quentinchampenois commented
Hi @paulinebessoles @armandfardeau , 

I have removed the migration from PR, it is ready for another review, thanks !

2021-03-08 11:51 UTC, paulinebessoles commented
Tested and approved by product!

2021-03-12 11:12 UTC, merged