Fix missing translations
OpenSourcePolitics/decidim-aws pull request #56
Opened 2021-03-08 14:52 UTC by armandfardeau

2021-03-08 14:58 UTC, Quentinchampenois requested changes

2021-03-08 14:58 UTC, Quentinchampenois commented on config/locales/fr.yml
> +        explanation: '<b>L''auteur d''une pétition ne peut être anonyme.</b><br/>
Hi, 

Could you fix the double simple quotes in values like this one  for example ?
```
L''auteur d''une pétition ne peut être anonyme.
```

Thanks !

2021-03-08 15:00 UTC, Quentinchampenois commented on config/locales/fr.yml
> +        explanation: '<b>L''auteur d''une pétition ne peut être anonyme.</b><br/>
To be more precise, I didn't check in local but I think they won't be escaped

2021-03-10 09:08 UTC, paulinebessoles commented
@armandfardeau could you review the PR so it can be merged?

2021-03-11 18:11 UTC, Quentinchampenois approved these changes

2021-03-11 18:11 UTC, Quentinchampenois commented on config/locales/fr.yml
> +        explanation: '<b>L''auteur d''une pétition ne peut être anonyme.</b><br/>
I have tested locally, I apologize it works well.

Seems good to me !

2021-03-11 18:11 UTC, merged