Fix signature type on Decidim initiatives
OpenSourcePolitics/decidim-aws pull request #67
Opened 2021-06-28 11:11 UTC by paulinebessoles

This PR aims to fix the migration error on Decidim initiative signature type.

2021-06-28 14:47 UTC, armandfardeau approved these changes

2021-07-15 13:04 UTC, armandfardeau requested changes

2021-07-15 13:04 UTC, armandfardeau commented on db/migrate/20210628110058_fix_type_on_decidim_initiatives.rb
> +
```suggestion

```

2021-07-15 13:39 UTC, armandfardeau approved these changes

2021-07-15 14:18 UTC, MoretS approved these changes

2021-07-15 14:19 UTC, MoretS approved these changes

2021-07-19 08:59 UTC, Quentinchampenois approved these changes

2021-07-19 09:00 UTC, merged